data/visualization.py, requirements.txt, utils/object_visualization.py
This PR serves to upload two possible objects to start playing (motorbike.obj and birdy.obj) with different quantity of points in the mesh.
Example of the visualization:
Moreover, I also send you a visualization script, which not only provides the above visuals, but already gives some methodology on how to upload the data and the mesh.
In particular, `mesh.points` can be turned into a numpy array for ease of handling the points.
=> Upload objects and visualization

meshnets/main.py, meshnets/utils/data_processing.py, requirements.txt
I replaced the custom Graph type by torch_geometric.data.Data. In our case, it is not necessary to have custom datatypes and will simplify the pipeline down the road.
=> Geometric data

meshnets/modules/model.py
Replaced custom Graph data by torch geometric Batch as input to the model
=> torch_geometric.data.Batch as input to model

meshnets/modules/decoder.py, meshnets/modules/encoder.py
Skeleton for encoder and decoder torch modules. I would appreciate feedback on the following:
Do you think it should return the predicted tensor like right now or instead the graph batch with modified node features ?
Should  this code be added to the main model file or it will make the file too large once the processor is also implemented ?
Should I code the MLPs individually for the encoder/decoder or make a common method s.a. make_mlp(widht_list) ?
=> Identity encoder decoder implementation

meshnets/main.py, meshnets/modules/decoder.py, meshnets/modules/encoder.py, meshnets/modules/model.py, meshnets/modules/processor.py
This PR implements a dummy MGN model, composed of an Identity encoder, Identity processor and Linear decoder. The modules have been modified to work with torch_geometric Batch produced from our dataloaders.
A pipeline for model inference is implemented in the main method. The inference on our dataset works as expected and respects the desired ouptut dimension. From there, I will implement a simple Lightning wrapper and integrate the dummy model and dataset in the MLFlow framework.
=> Dummy model

meshnets/modules/lightning_wrapper.py
This PR adds a simple lightning wrapper that works with the MGN model and the Batch from torch geometric.
=> simple lightning wrapper for the MGN model

meshnets/main.py, meshnets/modules/decoder.py, meshnets/modules/encoder.py, meshnets/modules/mlp.py, meshnets/modules/model.py
This PR adds an MLP class, representing a simple MLP defined by a list of layer widths. It offers the possibility to activate or not the last layer and to apply layer norm or not to it.
Additionally, the MGN encoder and decoder classes have been modified to include this new MLP class.
=> mlp class for encoder and decoder

meshnets/train.py, meshnets/utils/model_training.py
PR for the model training method and the main train file
=> added main train file and train_model method

meshnets/tune.py, meshnets/utils/model_training.py
I added a tuning main method and modified the model training method accordingly, following @AugustoPeres implementation of tuning using Ray and MLFlow.
=> added tuning main method and in model_training

meshnets/process.py, meshnets/utils/data_processing.py
This PR adds a main file to run data processing from mesh files to .pt files. The loop and saving dynamic is moved from utils to this main processing file.
=> added main data processing file

meshnets/modules/model.py, meshnets/modules/processor.py
This PR implements the MGN processor and integrates it in our model. The processor uses the torch-scatter library that currently causes problems in remote runs, so it might be changed later if a good alternative is found.
=> added MGN processor to the model

meshnets/runtime-conda.yml, requirements.txt
Updated requirements file to install the environment dependencies using pip
=> updated requirements file

meshnets/process.py, meshnets/utils/data_loading.py, meshnets/utils/data_processing.py
Small PR for name change of the arg `get_pressure` to `load_pressure`. Return type hint is also corrected for loading methods.
=> small changes to arg name and methods return hint

meshnets/train.py, meshnets/tune.py, meshnets/utils/model_training.py
PR to change the default flag values to work on the cluster.
=> default flags for cluster runs

meshnets/modules/lightning_wrapper.py, meshnets/utils/model_loading.py
PR to add a method that allows the loading of a model from mlflow
=> load model method

meshnets/process.py, meshnets/train.py, meshnets/tune.py
Modified the main processing file to make use of our new dataset implementation.
The processing file now consist only of the two following steps:
- instantiate a dataset class given the data directory
- use the built in processing method of our dataset class to create the processed .pt files
=> modified data processing and flag

meshnets/train.py, meshnets/tune.py
PR to correct the data_dir flag name when accessed
=> changed flag access

meshnets/utils/data_visualization.py
PR for three visualization methods for meshes and array field
=> Visualization

meshnets/utils/callbacks.py
Added a GPU Usage callback that only access usage at the logging step. This samples the gpu usage instead of computing a average like the previous one
=> added non-mean gpu usage callback

meshnets/modules/lightning_wrapper.py, meshnets/utils/model_training.py
PR for a new dynamic in the lightning wrapper parameters. We now give the model Class and model parameters to the wrapper.
This has multiple advantages:
- Modularity between wrapper and model is preserved
- Wrapper and model are instantiated together
- The wrapper is able to save the model parameter as hyperparameters
- The instantiated model is not saved to the checkpoints (this usually throws a warning due to bad memory use)
- We can still load the wrapper without providing the hyperparameters
=> new lightning wrapper params

meshnets/utils/callbacks.py
Changed the GPU usage metric names to the request of @AugustoPeres
=> changed gpu usage metric names

meshnets/eval.py, meshnets/utils/data_visualization.py, meshnets/visualize.py
PR for visualising a model prediction on a random mesh from a validation dataset, can be in or out of distribution
=> added main file for pred visualization

meshnets/train.py, meshnets/tune.py, meshnets/utils/callbacks.py, meshnets/utils/model_training.py
This PR implements the following unrelated  minor changes:
- changes default flag values in train/tune
- create an mlflow experiment in tune: if not, the experiment will be created multiple times in parallel by each worker
- log the batch size as hyperparam
- correct the checkpoint logger to properly finalise the mlflow logger
=> minor param and log changes

meshnets/modules/lightning_wrapper.py, meshnets/visualize.py
This PR add a method in the wrapper to unnormalize predictions when doing a forward pass. It also modifies the visualization file to follow this new implementation and offer the option to plot both normalized and unnormalized
=> added unnormalization in wrapper

meshnets/__init__.py, meshnets/datatypes/__init__.py, meshnets/modules/__init__.py, meshnets/utils/__init__.py, setup.py
Addresses issue #44.
Previews:
Install
Import and python autocomplete
=> Making meshnets a package.

meshnets/utils/data_visualization.py, meshnets/visualize.py
Adds the option to visualize the relative error in the visualization script.
We then call this function twice. The last time we clip the colorbar to the range [0, 1] to visualize where the error is greater than 1.
=> Visualizing relative error

meshnets/utils/datasets.py
Now we mainly use the interpolates .vtk files so I am changing the defaults
=> Changing default mesh_file_name name

data_generation/estimate_costs.py
This pull request adds a script to estimate the cost of one simulation. It submits just one tasks, wait for it to finish, gets the total time, and computes its cost.
Program output is as follows:
```
I1012 17:18:27.370823 140578044125248 machines.py:63] Registering machine group configuration with the API.
I1012 17:18:28.359893 140578044125248 machines.py:67] Registered machine group:
I1012 17:18:28.359977 140578044125248 machines.py:68]  > ID: bd36b6a1-617f-45e9-ab5c-6ad4f32587b3
I1012 17:18:28.360085 140578044125248 machines.py:69]  > Name: api-bd36b6a1-617f-45e9-ab5c-6ad4f32587b3
I1012 17:18:28.360340 140578044125248 machines.py:114] Starting a machine group. This may take up to a few minutes.
I1012 17:18:28.360370 140578044125248 machines.py:116] Note that stopping this local process …
```
=> Adding script to estimate the cost of a simulation

meshnets/data_processing/data_mappers.py, meshnets/data_processing/test_data_mappers.py
Add the function to compute the the edge features of a given graph.
Adds unit test for the expected result
=> Adding edge features function

meshnets/data_processing/data_mappers.py, meshnets/data_processing/test_data_mappers.py
Adds a function for node features. At the moment this is just the wind vector.
=> Added function to make the node features

meshnets/data_processing/__init__.py, meshnets/utils/model_training.py, scripts/train.py, scripts/tune.py
Adds the dataset normalization to training
=> Add back normalization to training

meshnets/utils/data_visualization.py, meshnets/utils/model_loading.py, scripts/visualize.py
Adds the option to fetch from other mlflow folders
=> Adds the option to fetch checkpoints from mlflow from other folders
